services:
  mysql:
    image: mysql:8.0
    container_name: database_theme
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: theme
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - msa-network

volumes:
  mysql-data:

networks:
  msa-network:
    driver: bridge
