server:
  port: 8080
spring:
  cloud:
    compatibility-verifier:
      enabled=false:
    loadbalancer:
      ribbon:
        enabled: false
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: gateway-service
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
